### ISSUE TITLE
Several items/texts not translated/localized

### ISSUE THREAD

**Issue by pryds** [OpenBazaar/OpenBazaar-Client#1179]
Brief Description: If a non-English locale is selected for the UI, there are several items and/or texts that still appear in English. These are the ones that I found:

![openbazaar-countries](https://cloud.githubusercontent.com/assets/4420584/14033937/d1a493da-f21e-11e5-8b95-13f5737111e2.png)

When creating a new listing (and throughout the rest of the app), the list of countries contains country names in English (and they do not appear in the language list for translation).

![openbazaar-option-eu](https://cloud.githubusercontent.com/assets/4420584/14033967/039c8500-f21f-11e5-9cff-2278806aaaf1.png)

When creating a new item, the text "Select an Option", the text "European Union", and the text "European Economic Area" are in English (and they do not appear in the language list for translation).

![openbazaar-amounts](https://cloud.githubusercontent.com/assets/4420584/14034001/3fb2865c-f21f-11e5-966a-50ec11a5d8ef.png)

Throughout the app, all BTC amounts are shown with English punctuation, although e.g. Danish is selected as UI locale. In Danish, comma is used as decimal separator instead of full-stop, so the English "1,000,000.00" would be written as "1.000.000,00" in Danish and other languages. "1.000 BTC" would mean 1000 BTC in Danish, but only 1 BTC in English, so this is not unimportant. Some languages have still other rules of punctuation, e.g. Swedish uses colon as decimal separator for prices. All decent internationalization software has functionality to handle localized numbers automatically; please enable this feature.

![openbazaar-dates](https://cloud.githubusercontent.com/assets/4420584/14034058/d1f59216-f21f-11e5-926e-118e5df5f341.png)

When creating a new listing (and possibly throughout the app), dates and times are written in English notion, even though a non-English UI locale is selected. In Danish, the date from the screenshot above (03/25/2016) would be written as 25-03-2016 (so Dates like 03/05 would be ambiguous). Also, we don't use "AM"/"PM" (it is quite out of place and confusing to see in a Danish UI), but instead the 24 hour system. Also, the month and week names are written in English. All decent internationalization software has functionality to handle localized dates and times automatically; please enable this feature.

Also, the text "mm/dd/yyyy" (when no date has been set) is displayed in English (and it does not appear in the language list for translation).

![openbazaar-timezones](https://cloud.githubusercontent.com/assets/4420584/14042271/b80ca656-f278-11e5-8960-58bea0b26e22.png)

In the Settings screen (and possibly throughout the app), time zone descriptions are in English. Internationalization software probably has functionality to handle this.

Operating System (OS and version): Ubuntu 14.04 LTS
OpenBazaar version (shown on `About OpenBazaar` page in menu): 1.0.10

Reproducible (Always / Almost Always / Sometimes / Rarely / Couldn't Reproduce): Always

Steps to reproduce:
1. Select a non-English locale (e.g. Danish)
2. See above.

**Comment by rmisio** [comment]
I believe we've fixed all these. @pryds Please let us know if we missed anything.

Re: unlocalized date / time. In the  screenshot you provided, we are using an html input of type `datetime-local`. So, as long as your OS has it's lang / region properly set (must be done in your OS settings, not just in the ob app), it should put the date and time in the correct format. For example, I've set my region to Poland and I get this:

![image](https://cloud.githubusercontent.com/assets/794517/15442284/df5d60f4-1e94-11e6-8c4b-d5855d4232cb.png)

**Comment by ghost** [comment]
@rmisio It's still missing localization of decimal mark on "Dispute / moderation fee" (see issue #1551 ).

**Comment by SamPatt** [comment]
Since that last remaining problem has a separate issue, I'm going to close this one.
