### ISSUE TITLE
Dark "Enter message..." in some pages

### ISSUE THREAD

**Issue by ghost** [OpenBazaar/OpenBazaar-Client#1269]
When visiting some pages, "Enter message..." text is shown in dark.

![enter message](https://cloud.githubusercontent.com/assets/10789865/14302676/e32bb61a-fb79-11e5-888b-383ffba2586d.png)

**Comment by drwasho** [comment]
This has been fixed in a recent commit. Next release will include the fix.

**Comment by ghost** [comment]
@drwasho Reopen issue. It is still not fixed on v1.1.2

![chat enter message](https://cloud.githubusercontent.com/assets/10789865/14371197/a30050e4-fd0b-11e5-9368-2882dab68d57.png)

**Comment by ghost** [comment]
@jjeffryes Please reopen this issue.

**Comment by jjeffryes** [comment]
@rhcastilhos I don't know how you are getting that result. I can't replicate it on my client.

**Comment by hoffmabc** [comment]
Light colored pages have this problem

**Comment by hoffmabc** [comment]
Try a page with the white theme

**Comment by jjeffryes** [comment]
Here's a white theme. Maybe it's OS specific?

![image](https://cloud.githubusercontent.com/assets/1584275/14479808/548581e4-00f0-11e6-8346-89abbacfb9aa.png)

**Comment by jjeffryes** [comment]
Aha. If you have a light theme, and you have advanced graphics on, and you have a low-contrast screen, it's hard to make out. I'll adjust it.
