### ISSUE TITLE
Short description is always null on followers/following tab

### ISSUE THREAD

**Issue by morebrownies** [OpenBazaar/OpenBazaar-Client#426]
Here's what I see when I output `<%- JSON.stringify(ob)  %>`

`{"avatar_hash":"ab55826a3843d73bf7e8776296a19d9ae4d64bd7","guid":"6a3efa536558f8192707b79d75dcf2b8cb52374d","handle":"@themes","name":"Themes","nsfw":false,"short_description":"","avatarURL":"http://localhost:18469/api/v1/get_image?hash=ab55826a3843d73bf7e8776296a19d9ae4d64bd7&guid=6a3efa536558f8192707b79d75dcf2b8cb52374d"}`

**Comment by drwasho** [comment]
I think this has been fixed @morebrownies and @jjeffryes ? Reopen if not.

**Comment by jjeffryes** [comment]
This is still an issue, it appears to be a problem in get_following and get_followers, neither one returns the short description data. 

@cpacia can that be added to those calls? If not, we can remove it from the UI so it doesn't show the placeholder, but that wouldn't be ideal.

**Comment by cpacia** [comment]
updated the server code

**Comment by jjeffryes** [comment]
@cpacia I see the short_description key in the data from the API, but it's blank for everyone.
