### ISSUE TITLE
Client within a client (meta client?)

### ISSUE THREAD

**Issue by JustinDrake** [OpenBazaar/OpenBazaar-Client#753]
Fun challenge for you: reproduce the following situation where an OpenBazaar client is within a client. (Solution below.)

![screen shot 2016-02-19 at 20 13 33](https://cloud.githubusercontent.com/assets/731743/13186199/5df53dd4-d745-11e5-99d6-da35b3ad3df0.png)

*
*
*
*
*

To reproduce:
- Go to the "About" pane
- Click on 'Tutorial' in the sentence "OpenBazaar version 1.0 Tutorial"

**Comment by morebrownies** [comment]
@SamPatt where would you like the tutorial link to link to? It's currently set to a href="" target=\"_blank\">Tutorial</a which is why the issue is happening

**Comment by SamPatt** [comment]
I'll send the link along soon.

**Comment by drwasho** [comment]
LOL!

**Comment by morebrownies** [comment]
Fixed

**Comment by drwasho** [comment]
@morebrownies is the fix in one your branches, because I still get this bug in `master`?

**Comment by morebrownies** [comment]
Yeah misc103, should be merged tomorrow.

**Comment by drwasho** [comment]
No problem.
